#!/usr/bin/with-contenv bash
# ==============================================================================
# Community Hass.io Add-ons: AppDaemon
# Runs the AppDaemon
# ==============================================================================
# shellcheck disable=SC1091
source /usr/lib/hassio-addons/base.sh

declare commtype
declare log_level
declare appdaemon_version

# Find the matching log level
case "$(hass.string.lower "$(hass.config.get 'log_level')")" in
    all|trace|debug)
        log_level="DEBUG"
        ;;
    info|notice)
        log_level="INFO"
        ;;
    warning)
        log_level="WARNING"
        ;;
    error)
        log_level="ERROR"
        ;;
    fatal|off)
        log_level="FATAL"
        ;;
esac

commtype=$(hass.string.upper "$(hass.config.get 'commtype')")
appdaemon_version=$(pip3 show appdaemon | awk -F"[ ',]+" '/Version: /{print $2}')
if [[ "$appdaemon_version" == '' ]]
    then
       echo "Appdaemon not installed"
       appdaemon_version="$(hass.config.get 'version')"
       echo "Installing AppDaemon" + "$appdaemon_version"
       pip3 install appdaemon=="$appdaemon_version"
fi
# Run the AppDaemon
case "$appdaemon_version" in
    3.*)
        appdaemon -c /config/appdaemon -D "${log_level}"
        ;;
    2.*)
        appdaemon -c /config/appdaemon -D "${log_level}" --commtype="${commtype}"
        ;;
esac

